apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "download.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "download.name" . }}
    helm.sh/chart: {{ include "download.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "download.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "download.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
           - name: nfs-253
             mountPath: /nfs253
          #   subPath: /test
          command: ['sh', '-c', '/nfs253/config/ngx_download/startdownload.sh']
         # command: ['sh', '-c', 'nginx -g "daemon off;"']
          env:
          - name: MYSQLHOST
            value: {{ .Values.MYSQLHOST }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: nfs-253
        nfs:
         server: {{ .Values.NFSSERVER }}
         path: "/"
