apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.0
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/etc/kubernetes/kubelet-plugins/volume/exec"
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - "k8sha.yunwei.edu"
  - "192.168.31.30"
  - "192.168.31.31"
  - "192.168.31.32"
  - "192.168.31.33"
  - "master1.yunwei.edu"
  - "master2.yunwei.edu"
  - "master3.yunwei.edu"
  - 127.0.0.1
controlPlaneEndpoint: "k8sha.yunwei.edu:8443"
etcd:
  external:
    endpoints:
    - https://192.168.31.31:2379
    - https://192.168.31.32:2379
    - https://192.168.31.33:2379
    caFile: /etc/etcd/ssl/ca.pem
    certFile: /etc/etcd/ssl/etcd.pem
    keyFile: /etc/etcd/ssl/etcd-key.pem
