registry:
  # Docker registry url
  url: http://repo:5000/v2
  # Docker registry fqdn
  name: repo:5000
  # To allow image delete, should be false
  readonly: false
  auth:
    # Disable authentication
    enabled: false
