apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
#  labels:
#    pv: mysql-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mysql-pv
    server: 192.168.253.3
